### ISSUE TITLE
bug fix null parameter

### ISSUE THREAD

**Issue by SodaSurfer** [hannesa2/paho.mqtt.android#531] opened 2023-11-26 08:18 UTC
hi
in MqttAndroidClient on `disconnected` method, we send a callback to connection lost with null reason:
https://github.com/hannesa2/paho.mqtt.android/blob/d6962010c43117e88bdb9ad85609ca32d2c462f9/serviceLibrary/src/main/java/info/mqtt/android/service/MqttAndroidClient.kt#L970C11-L970C11

but it raise an exception of: `Caused by java.lang.NullPointerException: Parameter specified as non-null is null`

because in the interface `MqttCallback` in `org.eclipse.paho.client.mqttv3` package, it must not be null:
https://eclipse.dev/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttCallback.html

so i gess it should be fixed with some none-null parameter, no?

**Comment by hannesa2** [comment] 2023-11-26 08:46
Please show me your exception

**Comment by SodaSurfer** [comment] 2023-11-26 09:22
this:
Caused by java.lang.NullPointerException: Parameter specified as non-null is null: parameter cause
       at connectionLost(MqttConnector.kt:1)
       at info.mqtt.android.service.MqttAndroidClient.disconnected ...
       at info.mqtt.android.service.MqttAndroidClient.onReceive ...

**Comment by hannesa2** [comment] 2023-11-26 10:58
Why do you remove line numbers and make it more difficult for me ?

Let's do it vice versa: 
This test is running fine https://github.com/hannesa2/paho.mqtt.android/blob/master/extendedSample/src/androidTest/java/info/mqtt/android/extsample/activity/ExtendedPublishTest.kt#L84-L105 without an issue.

Even running the extended sample and disconnect is fine 
<img width="1335" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/3314607/2a8c9918-bec4-4d71-990b-ba8be6c3ee9a">

For me it's a sign that the issue is located on your side.

I close this, and if you don't agree, please reopen it again

**Closed by hannesa2** 2023-11-26 10:58 UTC
