### ISSUE TITLE
gradle 8.+ enable Minify mqtt can't connect

### ISSUE THREAD

**Issue by ccominghome** [hannesa2/paho.mqtt.android#509] opened 2023-09-14 08:27 UTC
![CleanShot 2023-09-14 at 16 27 26@2x](https://github.com/hannesa2/paho.mqtt.android/assets/19590764/81c926a6-8214-4da6-bba8-fe2dcdf0e672)

(MqttAndroidClient.kt:887)Bundle[{.invocationContext=null, .errorMessage=Error locating the logging class, .exception=java.util.MissingResourceException: Error locating the logging class, .activityToken=0, .callbackAction=connect, .clientHandle=tcp://broker.hivemq.com:1883:BasicSample1694679906321:info.mqtt.java.example, .callbackStatus=ERROR}]
16:25:06.447  D  (MQTTExampleActivity.kt:81)Failed to connect: tcp://broker.hivemq.com:1883

**Comment by hannesa2** [comment] 2023-09-14 08:56
The basicSample doesn't work properly and there is too less information.
If you need help, you should provide a running example, which demonstrate the issue, in this repo as an pull request.

I close this, but you can reopen it again.

Btw, you should check your `LoggingTools.kt`

**Closed by hannesa2** 2023-09-14 08:56 UTC

**Comment by Makwana619** [comment] 2024-03-01 08:59
any fixes?

**Comment by hannesa2** [comment] 2024-03-01 10:14
https://github.com/hannesa2/paho.mqtt.android/issues/509#issuecomment-1719040483

**Comment by Lok1n8** [comment] 2024-03-29 01:42
same question

**Comment by hannesa2** [comment] 2024-03-29 09:28
I see it's better to add this to this library

**Comment by hannesa2** [comment] 2024-03-29 09:34
> solved by
> -keep class org.eclipse.paho.client.mqttv3.logging.JSR47Logger { *; }

This #592 should do it automatically

**Comment by hannesa2** [comment] 2024-03-30 07:03
> ![CleanShot 2023-09-14 at 16 27 26@2x](https://private-user-images.githubusercontent.com/19590764/267911177-81c926a6-8214-4da6-bba8-fe2dcdf0e672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODI0NDUsIm5iZiI6MTcxMTc4MjE0NSwicGF0aCI6Ii8xOTU5MDc2NC8yNjc5MTExNzctODFjOTI2YTYtODIxNC00ZGE2LWJiYTgtZmUyZGNkZjBlNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA3MDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MzIyNTVhNTkxMDI2M2I3N2M2NzkzZjdiZWUyM2Y0MjY0MWY4MzVhOGNhM2M4N2Y5ZmM0YWZlNDk0NWUxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-hjHED1fxuEgrwAxEop-NdTesBJ7hflul-6KWYF-ok0)
> 
> ```
> (MqttAndroidClient.kt:887)Bundle[{.invocationContext=null, .errorMessage=Error locating the logging class, .exception=java.util.MissingResourceException: Error locating the logging class, .activityToken=0, .callbackAction=connect, .clientHandle=tcp://broker.hivemq.com:1883:BasicSample1694679906321:info.mqtt.java.example, .callbackStatus=ERROR}]
> 16:25:06.447  D  (MQTTExampleActivity.kt:81)Failed to connect: tcp://broker.hivemq.com:1883
> ```

I can't reproduce this issue. What should I do, to see this ? @ccominghome

**Comment by ZouZLong** [comment] 2025-02-05 09:27
https://github.com/hannesa2/paho.mqtt.android/issues/509#issuecomment-2026452638

solve

**Comment by hannesa2** [comment] 2025-02-05 09:32
I guess there is no reason to do it on app side anymore https://github.com/hannesa2/paho.mqtt.android/pull/592
