### ISSUE TITLE
android.database.CursorWindowAllocationException

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [hannesa2/paho.mqtt.android#305] opened 2022-05-07 10:08 UTC
05-01 08:22:27.868 4394 6705 E CursorWindow: Could not allocate CursorWindow '/data/user/0/com.xxx.xxxx/databases/messageMQ' of size 2097152 due to error -12.
9705-01 08:22:27.868 4394 6705 E CrashHandler: In thread: Thread[arch_disk_io_4,5,main]
9805-01 08:22:27.868 4394 6705 E CrashHandler: UncaughtException detected: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
9905-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.CursorWindow.<init>(CursorWindow.java:108)
10005-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
10105-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
10205-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
10305-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
10405-01 08:22:27.868 4394 6705 E CrashHandler: at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
10505-01 08:22:27.868 4394 6705 E CrashHandler: at androidx.room.InvalidationTracker$1.checkUpdatedTable(InvalidationTracker.java:463)
10605-01 08:22:27.868 4394 6705 E CrashHandler: at androidx.room.InvalidationTracker$1.run(InvalidationTracker.java:433)
10705-01 08:22:27.868 4394 6705 E CrashHandler: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10805-01 08:22:27.868 4394 6705 E CrashHandler: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10905-01 08:22:27.868 4394 6705 E CrashHandler: at java.lang.Thread.run(Thread.java:818)

**Comment by LiWeiQiangAndroid** [comment] 2022-05-07 10:15
MqttService.onDestroy()   
messageDatabase.close()?

**Comment by hannesa2** [comment] 2022-05-07 10:22
In the past there was a similar error. Do you use most recent version ?

**Comment by LiWeiQiangAndroid** [comment] 2022-06-03 22:50
yes，room version 2.4.2

**Comment by hannesa2** [comment] 2022-06-04 03:45
> Could not allocate CursorWindow '/data/user/0/com.xxx.xxxx/databases/messageMQ' of size 2097152 due to error -12.
> CrashHandler: In thread: Thread[arch_disk_io_4,5,main]

If you can reproduce it, I recommend to log disk and memory situation,
In general, for me it looks like more an issue of Room itself and maybe a report to https://issuetracker.google.com/ makes sense

**Comment by LiWeiQiangAndroid** [comment] 2022-06-04 03:47
okay

**Comment by hannesa2** [comment] 2022-06-04 03:52
Currently in the stacktrace there is not code of `paho.mqtt.android` involved. If you know more details, you can reopen.
In the meanwhile I close this issue

**Closed by hannesa2** 2022-06-04 03:52 UTC

**Comment by LiWeiQiangAndroid** [comment] 2022-06-07 07:26
https://github.com/hannesa2/paho.mqtt.android/blob/master/serviceLibrary/src/main/java/info/mqtt/android/service/MqttService.kt#L215  ?

**Comment by hannesa2** [comment] 2022-06-07 11:19
https://github.com/hannesa2/paho.mqtt.android/pull/271
https://github.com/hannesa2/paho.mqtt.android/issues/269
