### ISSUE TITLE
AlarmPingServer error

### ISSUE THREAD

**Issue by augelloantonio** [hannesa2/paho.mqtt.android#411] opened 2022-12-15 10:24 UTC
I everyone, I have moved on this library and thanks for the effort and the work to keep alive PAHO based MQTT service that is not aligned with the latests versions.
I would share this issue with 3.6.0-beta4 version of the library:

```
E/WM-WorkerFactory: Could not instantiate info.mqtt.android.service.ping.AlarmPingSender$PingWorker
    java.lang.NoSuchMethodException: info.mqtt.android.service.ping.AlarmPingSender$PingWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getDeclaredConstructor(Class.java:2201)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
        at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
E/WM-WorkerWrapper: Could not create Worker info.mqtt.android.service.ping.AlarmPingSender$PingWorker

```
Fortunately I have a lot of exception that does the work around and foreground services that keep every part of my app awake and restore the connection every time somethings goes wrong.

From what i can see it keeps disconnecting at interval, can't say how often in minutes, and when the client reconnect the error happens, most often while in foreground.

**Comment by hannesa2** [comment] 2022-12-15 10:45
Thanks a lot to test and give feeback.
`java.lang.NoSuchMethodException: info.mqtt.android.service.ping.AlarmPingSender$PingWorker`

Hmm, maybe you use a release build and proguard obfuscated it ? Not sure if this is the reason, but why should this disappear ?
<img width="656" alt="image" src="https://user-images.githubusercontent.com/3314607/207839568-0cdd826c-2117-4667-aa95-e40b2d81523f.png">

**Comment by augelloantonio** [comment] 2022-12-16 09:28
Thanks for your answer, I don't use Proguard. It seems that is not happening with the version 3.5.1.

**Comment by hannesa2** [comment] 2022-12-16 09:48
Sure, `3.5.1` don't use `WorkManager` but keeps the phone always on. This comes with impact of battery duration.
To get rid of this battery issue is the main reason for `3.6.x`

**Comment by kundan1293** [comment] 2022-12-17 07:06
Hi everyone, I used 3.6.0-beta4 version of the library and I am facing the same issue.

**Comment by lotaviods** [comment] 2023-01-31 12:43
Same problem here using 3.6.0-beta2 running on debug version, without proguard 
![Captura de Tela 2023-01-31 às 09 43 20](https://user-images.githubusercontent.com/44534393/215763036-b8a3fdaa-e419-412f-8b10-2680a8cbec40.png)

**Comment by liuhuan0225** [comment] 2023-02-01 02:52
I'm having this problem too, has it been resolved?

**Comment by lotaviods** [comment] 2023-02-06 11:07
Anyone has some clue on what’s is happening?

**Comment by hannesa2** [comment] 2023-02-06 11:28
Can help someone to demonstrate issue with _runnig_ code ?

**Comment by lotaviods** [comment] 2023-02-06 14:42
I made a sample to reproduce this behavior, as i show in log, it take about 2 minutes to show this exception.

https://github.com/lotaviods/mqtt_example

<img width="943" alt="Captura de Tela 2023-02-06 às 11 36 14" src="https://user-images.githubusercontent.com/44534393/216999730-75dc8751-d183-47a5-b39f-ea146956b477.png">

**Comment by hannesa2** [comment] 2023-02-06 17:34
<html><head></head><body>

`3.6.0-beta6` looks different now. At least no crash ! Please give it a try

I'm not sure about this `Task was cancelled`

</body></html>

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/3314607/217042372-44d7ac09-0f14-4ac6-8a28-01e37d554793.png">

**Comment by hannesa2** [comment] 2023-02-06 17:34
Please provide some feedback

**Comment by lotaviods** [comment] 2023-02-06 18:33
Yes, with 3.6.0-beta6 now doesn’t crash just logging cancelled task as above

**Comment by hannesa2** [comment] 2023-02-06 19:52
> I'm not sure about this `Task was cancelled`

Is this an issue, or not ?

**Comment by lotaviods** [comment] 2023-02-07 11:33
Giving that PingWorker is doing its job i don’t think so

**Comment by hannesa2** [comment] 2023-02-09 05:28
It looks like `3.6.0-beta6` solved this. That's why I close this issue, and please reopen it again, if there is still some issue with this.

Btw, if you think it's time to merge it to master, because it's work properly, please inform me

**Closed by hannesa2** 2023-02-09 05:28 UTC
Labels: WorkMananger
